import React from 'react';
import DemoAnchor, {Anchor, GitHubAnchor} from "../parts/Anchors.jsx";


export const toolDefn = {
    "title": "Documentation: Build Framework",
    "toolDocs": null,
};

function Build() {
    return (
        <div>
            <h2>General Build</h2>
            <div>
                <ul>
                    <li>
                        <Anchor path="https://www.gnu.org/software/make/manual/html_node/index.html">GNU Make</Anchor>
                        : Depends on <DemoAnchor path=".env"/> which is generated by
                        <DemoAnchor path="bin/generateDotEnv.sh"/>
                    </li>
                    <li>
                        <Anchor path="https://docs.docker.com/reference/dockerfile/">Dockerfile</Anchor>'s
                        define the contents of each container image.
                    </li>
                    <li>
                        <Anchor path="https://docs.docker.com/reference/compose-file/">docker-compose.yml</Anchor>
                        file
                    </li>
                </ul>
            </div>
            <h2>Noteworthy Build Scripts</h2>
            <div>
                <b>fileWatcher.py</b>: File Monitor Utility for continuous build.
                <br/><GitHubAnchor path="KevinMatte/fileWatcher"/>
                <br/>
                Monitor's paths and files and executes commands when they change.
                An original version of this is used in <DemoAnchor path="bin/monitorBuild.sh"/>
            </div>
        </div>
    )
}

export default Build;
